# Generated by Django 6.0.3 on 2026-04-02 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('session', 'Session'), ('period', 'Period')], max_length=16)),
                ('evaluation_start_date', models.DateField(blank=True, null=True)),
                ('evaluation_end_date', models.DateField(blank=True, null=True)),
                ('included_session_ids', models.JSONField(blank=True, default=list)),
                ('requested_by_user', models.BooleanField(default=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('llm_model', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('input_json', models.JSONField(blank=True, default=dict)),
                ('evaluation_json', models.JSONField(blank=True, default=dict)),
                ('summary_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_evaluations', to=settings.AUTH_USER_MODEL)),
                ('workout_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='training.workoutsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
