# Generated by Django 6.0.3 on 2026-04-03 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('source_dataset', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('modality', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('cable', 'Cable'), ('kettlebell', 'Kettlebell'), ('band', 'Band'), ('mobility', 'Mobility'), ('cardio', 'Cardio'), ('other', 'Other')], default='other', max_length=24)),
                ('library_role', models.CharField(choices=[('main', 'Main'), ('warmup', 'Warmup'), ('both', 'Both')], default='main', max_length=16)),
                ('equipment', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('movement_pattern', models.CharField(blank=True, max_length=160)),
                ('primary_muscles', models.JSONField(blank=True, default=list)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('stabilizers', models.JSONField(blank=True, default=list)),
                ('unilateral', models.BooleanField(default=False)),
                ('is_static', models.BooleanField(default=False)),
                ('supports_reps', models.BooleanField(default=True)),
                ('supports_time', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True)),
                ('instructions_status', models.CharField(choices=[('missing', 'Missing'), ('seeded', 'Seeded'), ('ai_draft', 'AI draft'), ('reviewed', 'Reviewed')], default='missing', max_length=16)),
                ('instruction_source', models.CharField(blank=True, max_length=64)),
                ('default_video_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='ManualProgramDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('goal_summary', models.CharField(blank=True, max_length=500)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=8)),
                ('weight_unit', models.CharField(default='kg', max_length=2)),
                ('program_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_manual_drafts', to='programs.trainingprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_program_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ManualProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_key', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('day_type', models.CharField(choices=[('training', 'Training'), ('rest', 'Rest'), ('cardio', 'Cardio'), ('mobility', 'Mobility'), ('rehab', 'Rehab')], default='training', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.manualprogramdraft')),
            ],
            options={
                'ordering': ('day_key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ManualProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('warmup', 'Warmup'), ('main', 'Main')], default='main', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('prescription_type', models.CharField(choices=[('reps', 'Reps'), ('time', 'Time')], default='reps', max_length=8)),
                ('sets_count', models.PositiveSmallIntegerField(default=3)),
                ('target_reps', models.CharField(blank=True, max_length=20)),
                ('target_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('load_guidance', models.CharField(blank=True, max_length=100)),
                ('target_effort_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rest_seconds_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_exercises', to='programs.manualprogramday')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_program_entries', to='programs.exercise')),
            ],
            options={
                'ordering': ('block_type', 'order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='manualprogramday',
            constraint=models.UniqueConstraint(fields=('draft', 'day_key'), name='unique_manual_day_per_draft'),
        ),
    ]
