# Generated by Django 6.0.3 on 2026-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_exercise_manualprogramdraft_manualprogramday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='generated_image',
            field=models.ImageField(blank=True, upload_to='exercise_images/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_status',
            field=models.CharField(choices=[('missing', 'Missing'), ('ai_draft', 'AI draft'), ('reviewed', 'Reviewed'), ('failed', 'Failed')], default='missing', max_length=16),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
