# Generated by Django 6.0.3 on 2026-04-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_exercise_generated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='brand',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='exercise',
            name='line',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exercise',
            name='raw_catalog_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
