# Generated by Django 6.0.3 on 2026-04-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_exercise_brand_exercise_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='canonical_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_variants', to='programs.exercise'),
        ),
    ]
