# Generated by Django 6.0.3 on 2026-04-06 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_exercise_canonical_exercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source_kind',
            field=models.CharField(choices=[('system', 'System'), ('catalog', 'Catalog'), ('user_submitted', 'User submitted'), ('ai_suggested', 'AI suggested')], default='system', max_length=24),
        ),
        migrations.AddField(
            model_name='exercise',
            name='verification_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending_review', 'Pending review'), ('rejected', 'Rejected')], default='approved', max_length=24),
        ),
        migrations.AddField(
            model_name='exercise',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
