# Generated by Django 6.0.3 on 2026-04-07 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_program_drafts(apps, schema_editor):
    ManualProgramDraft = apps.get_model('programs', 'ManualProgramDraft')
    ManualProgramDay = apps.get_model('programs', 'ManualProgramDay')
    ManualProgramExercise = apps.get_model('programs', 'ManualProgramExercise')
    ProgramDraft = apps.get_model('programs', 'ProgramDraft')
    ProgramDraftDay = apps.get_model('programs', 'ProgramDraftDay')
    ProgramDraftExercise = apps.get_model('programs', 'ProgramDraftExercise')

    draft_map = {}
    for legacy_draft in ManualProgramDraft.objects.all().order_by('id'):
        draft = ProgramDraft.objects.create(
            user_id=legacy_draft.user_id,
            name=legacy_draft.name,
            goal_summary=legacy_draft.goal_summary,
            duration_weeks=legacy_draft.duration_weeks,
            weight_unit=legacy_draft.weight_unit,
            program_notes=legacy_draft.program_notes,
            source='manual',
            status='published' if legacy_draft.published_program_id else 'draft',
            published_at=legacy_draft.published_at,
            published_program_id=legacy_draft.published_program_id,
            created_at=legacy_draft.created_at,
            updated_at=legacy_draft.updated_at,
        )
        draft_map[legacy_draft.id] = draft.id

    day_map = {}
    for legacy_day in ManualProgramDay.objects.all().order_by('id'):
        draft_id = draft_map.get(legacy_day.draft_id)
        if not draft_id:
            continue
        day = ProgramDraftDay.objects.create(
            draft_id=draft_id,
            day_key=legacy_day.day_key,
            name=legacy_day.name,
            day_type=legacy_day.day_type,
            notes=legacy_day.notes,
        )
        day_map[legacy_day.id] = day.id

    entries_to_create = []
    for legacy_entry in ManualProgramExercise.objects.select_related('exercise').all().order_by('id'):
        day_id = day_map.get(legacy_entry.day_id)
        if not day_id:
            continue
        exercise = legacy_entry.exercise
        entries_to_create.append(
            ProgramDraftExercise(
                day_id=day_id,
                exercise_id=legacy_entry.exercise_id,
                snapshot_external_id=exercise.external_id,
                snapshot_name=exercise.name,
                snapshot_modality=exercise.modality,
                snapshot_focus=', '.join((exercise.primary_muscles or [])[:2]),
                snapshot_instructions=exercise.instructions,
                snapshot_image_url=exercise.image_url,
                snapshot_video_url=exercise.default_video_url,
                snapshot_category=exercise.category,
                snapshot_brand=exercise.brand,
                snapshot_line=exercise.line,
                snapshot_supports_reps=exercise.supports_reps,
                snapshot_supports_time=exercise.supports_time,
                block_type=legacy_entry.block_type,
                order=legacy_entry.order,
                prescription_type=legacy_entry.prescription_type,
                sets_count=legacy_entry.sets_count,
                target_reps=legacy_entry.target_reps,
                target_seconds=legacy_entry.target_seconds,
                load_guidance=legacy_entry.load_guidance,
                target_effort_rpe=legacy_entry.target_effort_rpe,
                rest_seconds_override=legacy_entry.rest_seconds_override,
                notes=legacy_entry.notes,
                created_at=legacy_entry.created_at,
                updated_at=legacy_entry.updated_at,
            )
        )
    ProgramDraftExercise.objects.bulk_create(entries_to_create)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_exercise_created_by_exercise_review_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('goal_summary', models.CharField(blank=True, max_length=500)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=8)),
                ('weight_unit', models.CharField(default='kg', max_length=2)),
                ('program_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_seeded', 'AI seeded'), ('hybrid', 'Hybrid')], default='manual', max_length=16)),
                ('request_prompt', models.TextField(blank=True)),
                ('ai_context_notes', models.TextField(blank=True)),
                ('last_ai_action', models.CharField(blank=True, max_length=64)),
                ('latest_ai_evaluation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_program_drafts', to='programs.trainingprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProgramDraftAiRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64)),
                ('scope_payload', models.JSONField(blank=True, default=dict)),
                ('prompt_text', models.TextField(blank=True)),
                ('llm_model', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('raw_llm_response', models.TextField(blank=True)),
                ('validated_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('token_usage_input', models.PositiveIntegerField(blank=True, null=True)),
                ('token_usage_output', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='programs.programdraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_draft_ai_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProgramDraftDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_key', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('day_type', models.CharField(choices=[('training', 'Training'), ('rest', 'Rest'), ('cardio', 'Cardio'), ('mobility', 'Mobility'), ('rehab', 'Rehab')], default='training', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('ai_locked', models.BooleanField(default=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.programdraft')),
            ],
            options={
                'ordering': ('day_key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProgramDraftExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_external_id', models.CharField(blank=True, max_length=64)),
                ('snapshot_name', models.CharField(max_length=160)),
                ('snapshot_modality', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('cable', 'Cable'), ('kettlebell', 'Kettlebell'), ('band', 'Band'), ('mobility', 'Mobility'), ('cardio', 'Cardio'), ('other', 'Other')], default='other', max_length=24)),
                ('snapshot_focus', models.CharField(blank=True, max_length=300)),
                ('snapshot_instructions', models.TextField(blank=True)),
                ('snapshot_image_url', models.URLField(blank=True)),
                ('snapshot_video_url', models.URLField(blank=True)),
                ('snapshot_category', models.CharField(blank=True, max_length=120)),
                ('snapshot_brand', models.CharField(blank=True, max_length=80)),
                ('snapshot_line', models.CharField(blank=True, max_length=120)),
                ('snapshot_supports_reps', models.BooleanField(default=True)),
                ('snapshot_supports_time', models.BooleanField(default=False)),
                ('block_type', models.CharField(choices=[('warmup', 'Warmup'), ('main', 'Main')], default='main', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('prescription_type', models.CharField(choices=[('reps', 'Reps'), ('time', 'Time')], default='reps', max_length=8)),
                ('sets_count', models.PositiveSmallIntegerField(default=3)),
                ('target_reps', models.CharField(blank=True, max_length=20)),
                ('target_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('load_guidance', models.CharField(blank=True, max_length=100)),
                ('target_effort_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rest_seconds_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('ai_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_exercises', to='programs.programdraftday')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_draft_entries', to='programs.exercise')),
            ],
            options={
                'ordering': ('block_type', 'order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='programdraftday',
            constraint=models.UniqueConstraint(fields=('draft', 'day_key'), name='unique_program_draft_day_per_draft'),
        ),
        migrations.RunPython(backfill_program_drafts, noop_reverse),
    ]
