# Generated by Django 6.0.3 on 2026-04-07 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_programdraft_programdraftairun_programdraftday_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDraftRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('system', 'System')], default='system', max_length=16)),
                ('action_type', models.CharField(max_length=64)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('draft_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('ai_request_payload', models.JSONField(blank=True, default=dict)),
                ('ai_response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_draft_revisions', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='programs.programdraft')),
            ],
            options={
                'ordering': ('-created_at', '-revision_number'),
                'constraints': [models.UniqueConstraint(fields=('draft', 'revision_number'), name='unique_program_draft_revision_number')],
            },
        ),
    ]
