# Generated by Django 6.0.3 on 2026-04-02 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_day_key', models.CharField(max_length=16)),
                ('planned_day_label', models.CharField(blank=True, max_length=32)),
                ('planned_day_name', models.CharField(max_length=120)),
                ('workout_date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('session_json', models.JSONField(blank=True, default=dict)),
                ('submission_version', models.PositiveIntegerField(default=0)),
                ('last_exercise_submission_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='programs.trainingprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-workout_date', '-updated_at'),
                'constraints': [models.UniqueConstraint(fields=('user', 'program', 'workout_date', 'planned_day_key'), name='unique_workout_session_per_user_program_day')],
            },
        ),
    ]
